### ISSUE TITLE
2.6.48.4

### ISSUE THREAD

**Issue by jerrytang67** [jerrytang67/helloworld#2]
struct TSLEncryptDataObj
{
uint64_t ptrs[0x2B];
uint16_t enc_index;
byte unk2[0x6];
uint16_t enc_xor;
byte unk3[0x6];
};

auto encrypted_actor = m_kReader->readType<TSLEncryptDataObj>(m_AActorPtr + (i * sizeof(TSLEncryptDataObj)), PROTO_NORMAL_READ);
uint64_t tablePtr = 0x397B5A0 + m_kReader->getPUBase();
uint16_t decoded_xor = encrypted_actor.enc_xor ^ 0xCBAC;
int64_t Decoded_Index = encrypted_actor.enc_index ^ 0xD7AF5ABC;

		auto Xor1 = m_kReader->readType<DWORD>(tablePtr + sizeof(DWORD)*((byte)(Decoded_Index)+0x300), PROTO_NORMAL_READ);
		auto Xor2 = m_kReader->readType<DWORD>(tablePtr + sizeof(DWORD)*((byte)((DWORD_PTR)Decoded_Index >> 0x8) + 0x200), PROTO_NORMAL_READ);
		auto Xor3 = m_kReader->readType<DWORD>(tablePtr + sizeof(DWORD)*((byte)((DWORD_PTR)Decoded_Index >> 0x10) + 0x100), PROTO_NORMAL_READ);
		auto Xor4 = m_kReader->readType<DWORD>(tablePtr + sizeof(DWORD)*((DWORD_PTR)(Decoded_Index >> 0x18)), PROTO_NORMAL_READ);
		int64_t Real_index = (Xor1 ^ Xor2 ^ Xor3 ^ ~Xor4) % 0x2B;
				    
		int64_t curActor = encrypted_actor.ptrs[Real_index] ^ decoded_xor ;

**Comment by fwf02** [comment]
can you add this? + where KReader.cs?
